# SPDX-FileCopyrightText: 2022 Free Software Foundation Europe e.V. <https://fsfe.org>
#
# SPDX-License-Identifier: CC0-1.0

name: REUSE Compliance Check

on: [push, pull_request]

jobs:
  launch_command:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install reuse
        run: |
          pip3 install --user reuse

      - name: List Repos
        id: list_repos
        run: |
          org_name="InditexTech" # Reemplaza 'myOrg' con el nombre de tu organización
          token="${{ secrets.GITHUB_TOKEN }}"
          curl -s -H "Authorization: token $token" "https://api.github.com/orgs/$org_name/repos?type=all" | jq -r '.[].ssh_url' > repos.txt

      - name: Launch Command on Repos
        run: |
          while IFS= read -r repo; do
            repo_name=$(basename "$repo" ".git")
            echo "Cloning and launching command in $repo_name"
            # git clone https://$token@github.com/$org_name/$repo_name
            # (cd $repo_name && reuse lint || true)
          done < repos.txt
