name: Scorecards supply-chain security
on: [push]

# Declare default permissions as read only.
permissions: read-all

jobs:
  analysis:
    name: "Scorecard"
    runs-on: "ubuntu-latest"
    permissions:
      security-events: write
      id-token: write
      contents: read
      actions: read

    steps:
      - name: "Checkout repository"
        uses: actions/checkout@b32f140b0c872d58512e0a66172253c302617b90 # v4.0.0
        with:
          persist-credentials: false

      - name: "Run Scorecard"
        uses: ossf/scorecard-action@483ef80eb98fb506c348f7d62e28055e49fe2398 # v2.3.0
        with:
          results_file: results.sarif
          results_format: sarif
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          publish_results: true
